name: 'WordPress Plugin & Theme Publish to Repository'
description: 'Github workflow for deploying Wordpress plugin and theme zip to repo'
author: 'Manuel Bachl | AppMinds.dev'

branding:
  icon: 'archive'
  color: 'blue'

inputs:
  slug:
    required: false
    description: 'Name of the zip archive'
    default: ${GITHUB_REPOSITORY#*/}
  host:
    required: true
    description: 'Repository host'
  port:
    required: false
    description: 'SSH port'
    default: '22'
  username:
    required: true
    description: 'SSH username'
  password:
    required: true
    description: 'SSH password'

runs:
  using: 'composite'
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: .

    - name: List artifacts
      run: |
        cd ./${{ inputs.slug }}
        ls -la
        echo $(pwd)
      shell: bash

    - name: Deploy to FTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        source: "./${{ inputs.slug }}/${{ inputs.slug }}.zip"
        target: "/public_html/repo.appminds.dev/wp/packages"